function [out1,out2,out3,out4,out5,out6] = fduds(Hx,Hy,Hz,sxx,syy,szz,syz,szx,sxy)
%FDUDS
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6] = FDUDS(HX,HY,HZ,SXX,SYY,SZZ,SYZ,SZX,SXY)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    03-Mar-2017 08:54:15

out1 = 0.0;
if nargout > 1
    out2 = 0.0;
end
if nargout > 2
    out3 = 0.0;
end
if nargout > 3
    out4 = 0.0;
end
if nargout > 4
    out5 = 0.0;
end
if nargout > 5
    out6 = 0.0;
end
