function [out1,out2,out3] = fdudh(Hx,Hy,Hz,sxx,syy,szz,syz,szx,sxy)
%FDUDH
%    [OUT1,OUT2,OUT3] = FDUDH(HX,HY,HZ,SXX,SYY,SZZ,SYZ,SZX,SXY)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    03-Mar-2017 08:54:12

t2 = Hx.^2;
t3 = Hy.^2;
t4 = Hz.^2;
t5 = t2+t3+t4;
t6 = 1.0./sqrt(t5);
out1 = Hx.*t6;
if nargout > 1
    out2 = Hy.*t6;
end
if nargout > 2
    out3 = Hz.*t6;
end
