function [out1,out2,out3] = fdvdh(Hx,Hy,Hz,sxx,syy,szz,syz,szx,sxy)
%FDVDH
%    [OUT1,OUT2,OUT3] = FDVDH(HX,HY,HZ,SXX,SYY,SZZ,SYZ,SZX,SXY)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    03-Mar-2017 08:54:12

t2 = Hx.^2;
t3 = Hy.^2;
t4 = Hz.^2;
t5 = t2+t3+t4;
t6 = syy.*(1.0./3.0);
t7 = szz.*(1.0./3.0);
t15 = sxx.*(2.0./3.0);
t8 = t6+t7-t15;
t9 = sxx.*(1.0./3.0);
t20 = syy.*(2.0./3.0);
t10 = t7+t9-t20;
t11 = 1.0./t5;
t12 = 1.0./t5.^2;
t13 = Hy.*sxy;
t14 = Hz.*szx;
t30 = Hx.*t8;
t16 = t13+t14-t30;
t17 = Hx.*t16.*(3.0./2.0);
t18 = Hx.*sxy;
t19 = Hz.*syz;
t31 = Hy.*t10;
t21 = t18+t19-t31;
t22 = Hy.*t21.*(3.0./2.0);
t23 = Hx.*szx;
t24 = Hy.*syz;
t29 = szz.*(2.0./3.0);
t25 = t6+t9-t29;
t32 = Hz.*t25;
t26 = t23+t24-t32;
t27 = Hz.*t26.*(3.0./2.0);
t28 = t17+t22+t27;
out1 = t11.*(Hy.*sxy.*3.0+Hz.*szx.*3.0-Hx.*t8.*3.0)-Hx.*t12.*t28.*2.0;
if nargout > 1
    out2 = t11.*(Hx.*sxy.*3.0+Hz.*syz.*3.0-Hy.*t10.*3.0)-Hy.*t12.*t28.*2.0;
end
if nargout > 2
    out3 = t11.*(Hx.*szx.*3.0+Hy.*syz.*3.0-Hz.*t25.*3.0)-Hz.*t12.*t28.*2.0;
end
