function [out1,out2,out3,out4,out5,out6] = fdvds(Hx,Hy,Hz,sxx,syy,szz,syz,szx,sxy)
%FDVDS
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6] = FDVDS(HX,HY,HZ,SXX,SYY,SZZ,SYZ,SZX,SXY)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    03-Mar-2017 08:54:15

t2 = Hx.^2;
t3 = Hy.^2;
t4 = Hz.^2;
t5 = t2+t3+t4;
t6 = 1.0./t5;
t7 = t4.*(1.0./2.0);
t8 = t2.*(1.0./2.0);
t9 = t3.*(1.0./2.0);
out1 = -t6.*(-t2+t7+t9);
if nargout > 1
    out2 = -t6.*(-t3+t7+t8);
end
if nargout > 2
    out3 = -t6.*(-t4+t8+t9);
end
if nargout > 3
    out4 = Hy.*Hz.*t6.*(3.0./2.0);
end
if nargout > 4
    out5 = Hx.*Hz.*t6.*(3.0./2.0);
end
if nargout > 5
    out6 = Hx.*Hy.*t6.*(3.0./2.0);
end
