function [out1,out2,out3] = fdwdh(Hx,Hy,Hz,sxx,syy,szz,syz,szx,sxy)
%FDWDH
%    [OUT1,OUT2,OUT3] = FDWDH(HX,HY,HZ,SXX,SYY,SZZ,SYZ,SZX,SXY)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    03-Mar-2017 08:54:14

t2 = szz.*(1.0./3.0);
t3 = sxx.*(1.0./3.0);
t4 = syy.*(1.0./3.0);
t6 = syy.*(2.0./3.0);
t5 = t2+t3-t6;
t7 = sxy.*t5;
t12 = sxx.*(2.0./3.0);
t8 = t2+t4-t12;
t9 = sxy.*t8;
t29 = syz.*szx;
t10 = t7+t9-t29;
t14 = szz.*(2.0./3.0);
t11 = t3+t4-t14;
t13 = sxy.^2;
t15 = szx.*t11;
t16 = szx.*t8;
t39 = sxy.*syz;
t17 = t15+t16-t39;
t18 = syz.*t11;
t19 = syz.*t5;
t31 = sxy.*szx;
t20 = t18+t19-t31;
t21 = syz.^2;
t22 = szx.^2;
t55 = Hy.*sxy;
t56 = Hz.*szx;
t57 = Hx.*t8;
t58 = t55+t56-t57;
t59 = Hx.*t58;
t60 = Hx.*sxy;
t61 = Hz.*syz;
t62 = Hy.*t5;
t63 = t60+t61-t62;
t64 = Hy.*t63;
t65 = Hx.*szx;
t66 = Hy.*syz;
t67 = Hz.*t11;
t68 = t65+t66-t67;
t69 = Hz.*t68;
t23 = t59+t64+t69;
t25 = Hx.^2;
t26 = Hy.^2;
t27 = Hz.^2;
t28 = t25+t26+t27;
t30 = Hx.*t10;
t32 = Hz.*t20;
t33 = t5.^2;
t34 = t13+t21+t33;
t35 = Hy.*t34;
t36 = t30+t32-t35;
t37 = Hy.*t36;
t38 = Hy.*t10;
t40 = Hz.*t17;
t41 = t8.^2;
t42 = t13+t22+t41;
t43 = Hx.*t42;
t44 = t38+t40-t43;
t45 = Hx.*t44;
t46 = Hx.*t17;
t47 = Hy.*t20;
t48 = t11.^2;
t49 = t21+t22+t48;
t50 = Hz.*t49;
t51 = t46+t47-t50;
t52 = Hz.*t51;
t53 = t37+t45+t52;
t54 = t28.*t53;
t70 = t23.^2;
t24 = t54+t70;
t71 = t24.^2;
t72 = t71.^(1.0./4.0);
t73 = 1.0./t28.^2;
t74 = 1.0./t71.^(3.0./4.0);
t75 = 1.0./t28;
out1 = Hx.*t72.*t73.*-2.0+t24.*t74.*t75.*(Hx.*t53.*2.0+t23.*(Hy.*sxy.*2.0+Hz.*szx.*2.0-Hx.*t8.*2.0).*2.0+t28.*(Hx.*t42.*-2.0+Hy.*t10.*2.0+Hz.*t17.*2.0)).*(1.0./2.0);
if nargout > 1
    out2 = Hy.*t72.*t73.*-2.0+t24.*t74.*t75.*(Hy.*t53.*2.0+t23.*(Hx.*sxy.*2.0+Hz.*syz.*2.0-Hy.*t5.*2.0).*2.0+t28.*(Hx.*t10.*2.0-Hy.*t34.*2.0+Hz.*t20.*2.0)).*(1.0./2.0);
end
if nargout > 2
    out3 = Hz.*t72.*t73.*-2.0+t24.*t74.*t75.*(Hz.*t53.*2.0+t23.*(Hx.*szx.*2.0+Hy.*syz.*2.0-Hz.*t11.*2.0).*2.0+t28.*(Hx.*t17.*2.0+Hy.*t20.*2.0-Hz.*t49.*2.0)).*(1.0./2.0);
end
