function [out1,out2,out3,out4,out5,out6] = fdwds(Hx,Hy,Hz,sxx,syy,szz,syz,szx,sxy)
%FDWDS
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6] = FDWDS(HX,HY,HZ,SXX,SYY,SZZ,SYZ,SZX,SXY)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    03-Mar-2017 08:54:18

t2 = szz.*(1.0./3.0);
t3 = sxx.*(1.0./3.0);
t4 = syy.*(1.0./3.0);
t6 = syy.*(2.0./3.0);
t5 = t2+t3-t6;
t7 = sxy.*t5;
t12 = sxx.*(2.0./3.0);
t8 = t2+t4-t12;
t9 = sxy.*t8;
t46 = syz.*szx;
t10 = t7+t9-t46;
t14 = szz.*(2.0./3.0);
t11 = t3+t4-t14;
t13 = sxy.^2;
t15 = szx.*t11;
t16 = szx.*t8;
t55 = sxy.*syz;
t17 = t15+t16-t55;
t18 = syz.*t11;
t19 = syz.*t5;
t48 = sxy.*szx;
t20 = t18+t19-t48;
t21 = syz.^2;
t22 = szx.^2;
t31 = Hy.*sxy;
t32 = Hz.*szx;
t33 = Hx.*t8;
t34 = t31+t32-t33;
t35 = Hx.*t34;
t36 = Hx.*sxy;
t37 = Hz.*syz;
t38 = Hy.*t5;
t39 = t36+t37-t38;
t40 = Hy.*t39;
t41 = Hx.*szx;
t42 = Hy.*syz;
t43 = Hz.*t11;
t44 = t41+t42-t43;
t45 = Hz.*t44;
t23 = t35+t40+t45;
t24 = Hx.^2;
t25 = Hy.^2;
t26 = Hz.^2;
t27 = t24+t25+t26;
t28 = syy.*(4.0./9.0);
t29 = sxx.*(2.0./9.0);
t30 = szz.*(4.0./9.0);
t47 = Hx.*t10;
t49 = Hz.*t20;
t50 = t5.^2;
t51 = t13+t21+t50;
t71 = Hy.*t51;
t52 = t47+t49-t71;
t53 = Hy.*t52;
t54 = Hy.*t10;
t56 = Hz.*t17;
t57 = t8.^2;
t58 = t13+t22+t57;
t72 = Hx.*t58;
t59 = t54+t56-t72;
t60 = Hx.*t59;
t61 = Hx.*t17;
t62 = Hy.*t20;
t63 = t11.^2;
t64 = t21+t22+t63;
t73 = Hz.*t64;
t65 = t61+t62-t73;
t66 = Hz.*t65;
t67 = t53+t60+t66;
t68 = t27.*t67;
t69 = t23.^2;
t70 = t68+t69;
t74 = Hy.*sxy.*(1.0./3.0);
t75 = syy.*(2.0./9.0);
t76 = szz.*(2.0./9.0);
t77 = Hx.*sxy.*(1.0./3.0);
t78 = t29-t30+t75;
t79 = Hz.*t78;
t80 = t26.*(1.0./3.0);
t81 = t70.^2;
t82 = 1.0./t81.^(3.0./4.0);
t83 = 1.0./t27;
t84 = Hz.*szx.*(1.0./3.0);
t85 = sxx.*(4.0./9.0);
t86 = Hz.*syz.*(1.0./3.0);
t87 = -t28+t29+t76;
t88 = Hy.*t87;
t89 = Hx.*szx.*(1.0./3.0);
t90 = Hy.*syz.*(1.0./3.0);
t91 = t24.*(1.0./3.0);
t92 = t25.*(1.0./3.0);
out1 = t70.*t82.*t83.*(t23.*(t24.*(-2.0./3.0)+t80+t92).*2.0+t27.*(Hy.*(t77+t88-Hz.*syz.*(2.0./3.0))+Hz.*(t79+t89-Hy.*syz.*(2.0./3.0))+Hx.*(t74+t84-Hx.*(sxx.*(-8.0./9.0)+t28+t30)))).*(-1.0./2.0);
if nargout > 1
    out2 = t70.*t82.*t83.*(t27.*(Hz.*(t79+t90-Hx.*szx.*(2.0./3.0))+Hx.*(t74-Hz.*szx.*(2.0./3.0)+Hx.*(sxx.*(-4.0./9.0)+t75+t76))+Hy.*(t77+t86-Hy.*(syy.*(-8.0./9.0)+t30+t85)))+t23.*(t25.*(-2.0./3.0)+t80+t91).*2.0).*(-1.0./2.0);
end
if nargout > 2
    out3 = t70.*t82.*t83.*(t27.*(Hy.*(t86+t88-Hx.*sxy.*(2.0./3.0))+Hx.*(t84-Hy.*sxy.*(2.0./3.0)+Hx.*(t75+t76-t85))+Hz.*(t89+t90-Hz.*(szz.*(-8.0./9.0)+t28+t85)))+t23.*(t26.*(-2.0./3.0)+t91+t92).*2.0).*(-1.0./2.0);
end
if nargout > 3
    out4 = t70.*t82.*t83.*(t27.*(Hz.*(t36+t37+Hy.*t8)+syz.*t25+Hx.*Hy.*szx)-Hy.*Hz.*t23.*2.0).*(-1.0./2.0);
end
if nargout > 4
    out5 = t70.*t82.*t83.*(t27.*(Hx.*(t41+t42+Hz.*t5)+szx.*t26+Hy.*Hz.*sxy)-Hx.*Hz.*t23.*2.0).*(-1.0./2.0);
end
if nargout > 5
    out6 = t70.*t82.*t83.*(t27.*(Hy.*(t31+t32+Hx.*t11)+sxy.*t24+Hx.*Hz.*syz)-Hx.*Hy.*t23.*2.0).*(-1.0./2.0);
end
