function out1 = fu(Hx,Hy,Hz,sxx,syy,szz,syz,szx,sxy)
%FU
%    OUT1 = FU(HX,HY,HZ,SXX,SYY,SZZ,SYZ,SZX,SXY)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    03-Mar-2017 08:54:11

out1 = sqrt(Hx.^2+Hy.^2+Hz.^2);
