function out1 = fv(Hx,Hy,Hz,sxx,syy,szz,syz,szx,sxy)
%FV
%    OUT1 = FV(HX,HY,HZ,SXX,SYY,SZZ,SYZ,SZX,SXY)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    03-Mar-2017 08:54:11

t2 = szz.*(1.0./3.0);
t3 = sxx.*(1.0./3.0);
t4 = syy.*(1.0./3.0);
out1 = (Hx.*(Hy.*sxy+Hz.*szx-Hx.*(sxx.*(-2.0./3.0)+t2+t4)).*(3.0./2.0)+Hy.*(Hx.*sxy+Hz.*syz-Hy.*(syy.*(-2.0./3.0)+t2+t3)).*(3.0./2.0)+Hz.*(Hx.*szx+Hy.*syz-Hz.*(szz.*(-2.0./3.0)+t3+t4)).*(3.0./2.0))./(Hx.^2+Hy.^2+Hz.^2);
