function out1 = fw(Hx,Hy,Hz,sxx,syy,szz,syz,szx,sxy)
%FW
%    OUT1 = FW(HX,HY,HZ,SXX,SYY,SZZ,SYZ,SZX,SXY)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    03-Mar-2017 08:54:12

t2 = szz.*(1.0./3.0);
t3 = sxx.*(1.0./3.0);
t4 = syy.*(1.0./3.0);
t6 = syy.*(2.0./3.0);
t5 = t2+t3-t6;
t7 = sxy.*t5;
t12 = sxx.*(2.0./3.0);
t8 = t2+t4-t12;
t9 = sxy.*t8;
t10 = t7+t9-syz.*szx;
t14 = szz.*(2.0./3.0);
t11 = t3+t4-t14;
t13 = sxy.^2;
t15 = szx.*t11;
t16 = szx.*t8;
t17 = t15+t16-sxy.*syz;
t18 = syz.*t11;
t19 = syz.*t5;
t20 = t18+t19-sxy.*szx;
t21 = syz.^2;
t22 = szx.^2;
t23 = Hx.*(Hy.*sxy+Hz.*szx-Hx.*t8)+Hy.*(Hx.*sxy+Hz.*syz-Hy.*t5)+Hz.*(Hx.*szx+Hy.*syz-Hz.*t11);
t25 = Hx.^2;
t26 = Hy.^2;
t27 = Hz.^2;
t28 = t25+t26+t27;
t24 = t28.*(Hx.*(Hy.*t10+Hz.*t17-Hx.*(t13+t22+t8.^2))+Hy.*(Hx.*t10+Hz.*t20-Hy.*(t13+t21+t5.^2))+Hz.*(Hx.*t17+Hy.*t20-Hz.*(t21+t22+t11.^2)))+t23.^2;
out1 = (t24.^2).^(1.0./4.0)./t28;
